### ISSUE TITLE
Bulk Upload: Year 3 Cities, Global Datasets (Part I)

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#143]
CSU downloaded and processed data and metadata are ready to be uploaded to the 2C Geonode for the Year 3 cities. This is a **partial** upload at this point; QA/QC is pending on the other data. Note that the metadata spreadsheets are located outside the data folders in the file hierarchy. 

Metadata spreadsheets and data folders are located here in the Google Drive: 

[https://drive.google.com/drive/u/0/folders/178_2KnedGcmk1ZeS_BObpfOjpLMAsj8X]

The following data and metadata are ready to go NOW; the rest will be ready soon:

- Year 3 Bounding Boxes Metadata
- Year 3 GHSL Metadata
- Year 3 HydroAnalysis Metadata

**Comment by sophialinn** [comment]
Corrections have been made to the layers below. The problem seems to be with either "spaces" or hyphens ("-") in the filenames:

Layers with errors for metadata:

boke: built-up area (data mask) : Failed to update
boke: built-up area (multi-temporal) : Failed to update
boke-kamsar: built-up area (multi-temporal) : Failed to update
indore: built-up area (multi-temporal) : Failed to update
kamsar: built-up area (multi-temporal) : Failed to update
pemba: built-up area (multi-temporal) : Failed to update
santa fe: built-up area (multi-temporal) : Failed to update
tijuana: built-up area (multi-temporal) : Failed to update

**Comment by sophialinn** [comment]
Corrections have been made to the following. Error seems to be a result of "stream" vs "streams" in the filenames vs the metadata filenames.

Layers with errors for metadata:
boke: distance to streams (modeled) : Failed to update
kamsar: distance to streams (modeled) : Failed to update
pemba: distance to streams (modeled) : Failed to update

**Comment by d3netxer** [comment]
Ok great. I re-ran the update metadata scripts, and it ran successfully for all of the datasets.

**Comment by sophialinn** [comment]
Excellent, Tom. Since you seem to be working on this right now (!), I will let you know that the next batch is ready to go too. They can be found in the same folder:

https://drive.google.com/drive/u/0/folders/178_2KnedGcmk1ZeS_BObpfOjpLMAsj8X

- Year 3 SRTM
- Year 3 WorldPop

You will see the metadata spreadsheets for each, and the data folders with the corresponding names. Let me know how it goes; I'll be curious. Thanks.

**Comment by d3netxer** [comment]
Okay I uploaded all the datasets successfully. The following below had errors with the metadata update script:

### Year 3 SRTM

indore: controur (20m) : Failed to update
Exception: Layer matching query does not exist.
indore: contour (30m) : Failed to update
Exception: Layer matching query does not exist.
indore: contour (50m) : Failed to update
Exception: Layer matching query does not exist.
indore: elevation : Failed to update
Exception: Layer matching query does not exist.
indore: hillshade : Failed to update
Exception: Layer matching query does not exist.
indore: slope : Failed to update
Exception: Layer matching query does not exist.
Kamsar: Elevation : Metadata updated!
kamsar: hillshade  : Failed to update
Exception: Layer matching query does not exist.
kamsar: site exposure index : Failed to update
Exception: Layer matching query does not exist.
kamsar: slope : Failed to update
Exception: Layer matching query does not exist.
kamsar: slope (percent rise) : Failed to update
Exception: Layer matching query does not exist.

### Year 3 Worldpop

darkhan: population 2010 : Failed to update
Exception: Layer matching query does not exist.
kamsar: population 2010 (adjusted) : Failed to update
Exception: Layer matching query does not exist.
kamsar: population 2014 (adjusted) : Failed to update
Exception: Layer matching query does not exist.

**Comment by d3netxer** [comment]
Also on another note, I fixed the thumbnail problem with the previous uploads. I figured out that I need to change the owner of the directory for the thumbnail files that get added after the script is run. 

The drawing on some of the thumbnails looks skewed at the edges, but I don't know what there can be done in these cases.

**Comment by sophialinn** [comment]
Multiple corrections have been made, either to filenames in the metadata or actual files were missing. Please run the scripts again. I believe there will be at least one that still isn't solved (darkhan: population 2010), but let's see what happens.

**Comment by d3netxer** [comment]
Okay, tomorrow I can try keeping the data on the server, but re-downloading the spreadsheets and re-running the scripts.

**Comment by sophialinn** [comment]
Sounds good. Thanks!

**Comment by d3netxer** [comment]
Ok great, all layers uploaded and metadata completed successfully

**Comment by sophialinn** [comment]
Really?? Amazing...

Thanks!

**Comment by sophialinn** [comment]
OK, I just checked the GeoNode. I can only see those new layers when I'm logged in; is that expected? Also, some of the thumbnails are funky, but perhaps you're still working on that. Good news: we've broken 1000 datasets with this new batch!

**Comment by d3netxer** [comment]
thanks for pointing this out Sophia. I forgot to re-run the permissions script after re-running the metadata scripts. I have re-run the permissions script, and it should have fixed the issue. yay!

**Comment by d3netxer** [comment]
which ones? Like Kamsar:Slope? Maybe the units, for example, in units of degrees, make the values render with very low contrast in the thumbnails? I think the raster datasets might use a few generic types of symbology that may not render all types of raster well.

**Comment by sophialinn** [comment]
Yes, that probably makes sense. That is, there's very little elevation or slope variation in Kamsar, but it's using the symbology from places that show more variation. Hmm. The black boxes just don't look so good though. Any ideas?

**Comment by d3netxer** [comment]
I am having trouble logging into the geoserver, if I could do this, the sld styles could probably be manually adjusted. 

I also noticed on the server is a script called 'fix_raster_styles.py' that seems like it could automatically adjust styles. I'm not sure how to run it however. Terranodo would probably know more about this.
